language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
before_script:
  - mysql -e 'create database myapp_test'
  - psql -c 'create database myapp_test' -U postgres
